spring:
  profiles:
    active: dev

---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: microservicecloud-config-nocol-dev
    
eureka:
  client: 
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka    
    
---

server:
  port: 8202
spring:
  profiles: test
  application:
    name: microservicecloud-config-nocol-test
    
eureka:
  client: 
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka